insert  into gifts (id, name, icon, caption) values ('0', 'actor_card', 'ic_gift_actor_card', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('1', 'alcohol', 'ic_gift_alcohol', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('2', 'cookbook', 'ic_gift_cookbook', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('3', 'art_card', 'ic_gift_art_card', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('4', 'autoregistrator', 'ic_gift_autoregistrator', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('5', 'backgammon', 'ic_gift_backgammon', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('6', 'bag_m', 'ic_gift_bag_m', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('7', 'bag_w', 'ic_gift_bag_w', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('8', 'baloon_card', 'ic_gift_baloon_card', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('9', 'belt', 'ic_gift_belt', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('10', 'bike', 'ic_gift_bike', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('11', 'billiards_card', 'ic_gift_billiards_card', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('12', 'book', 'ic_gift_book', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('13', 'buggy_driving', 'ic_gift_buggy_driving', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('14', 'camera', 'ic_gift_camera', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('15', 'ceramic_teapot', 'ic_gift_ceramic_teapot', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('16', 'cigars', 'ic_gift_cigars', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('17', 'clothes_m', 'ic_gift_clothes_m', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('18', 'concert_tikets', 'ic_gift_concert_tikets', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('19', 'cookies_form', 'ic_gift_cookies_form', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('20', 'cosmetics_m', 'ic_gift_cosmetics_m', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('21', 'diary', 'ic_gift_diary', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('22', 'dishes2', 'ic_gift_dishes2', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('23', 'dishes', 'ic_gift_dishes', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('24', 'djlessons_card', 'ic_gift_djlessons_card', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('25', 'drivinglessons_card', 'ic_gift_drivinglessons_card', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('26', 'drums_card', 'ic_gift_drums_card', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('27', 'electric_shaver', 'ic_gift_electric_shaver', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('28', 'ereader', 'ic_gift_ereader', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('29', 'excursion_card', 'ic_gift_excursion_card', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('30', 'extreme_driving_card', 'ic_gift_extreme_driving_card', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('31', 'fishing_card', 'ic_gift_fishing_card', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('32', 'fishing', 'ic_gift_fishing', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('33', 'flashmemory', 'ic_gift_flashmemory', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('34', 'food_processor', 'ic_gift_food_processor', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('35', 'foot_warmer', 'ic_gift_foot_warmer', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('36', 'game_for_couple', 'ic_gift_game_for_couple', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('37', 'gamesclub_card', 'ic_gift_gamesclub_card', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('38', 'glasses', 'ic_gift_glasses', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('39', 'grilkit', 'ic_gift_grilkit', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('40', 'guitarlessons_card', 'ic_gift_guitarlessons_card', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('41', 'gym_m', 'ic_gift_gym_m', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('42', 'gym_w', 'ic_gift_gym_w', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('43', 'headphones', 'ic_gift_headphones', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('44', 'health_m', 'ic_gift_health_m', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('45', 'health_w', 'ic_gift_health_w', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('46', 'itrest_card', 'ic_gift_itrest_card', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('47', 'jeverly_box', 'ic_gift_jeverly_box', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('48', 'juicer', 'ic_gift_juicer', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('49', 'karting_card', 'ic_gift_karting_card', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('50', 'keyholder', 'ic_gift_keyholder', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('51', 'laptop', 'ic_gift_laptop', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('52', 'magicball', 'ic_gift_magicball', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('53', 'massage_card', 'ic_gift_massage_card', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('54', 'massager', 'ic_gift_massager', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('55', 'mirror', 'ic_gift_mirror', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('56', 'model', 'ic_gift_model', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('57', 'pan', 'ic_gift_pan', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('58', 'parfume_m_1', 'ic_gift_parfume_m_1', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('59', 'parfume_m', 'ic_gift_parfume_m', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('60', 'phone_m', 'ic_gift_phone_m', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('61', 'phone_w', 'ic_gift_phone_w', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('62', 'photo_card', 'ic_gift_photo_card', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('63', 'poncho', 'ic_gift_poncho', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('64', 'pottery_card', 'ic_gift_pottery_card', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('65', 'ps', 'ic_gift_ps', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('66', 'purse', 'ic_gift_purse', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('67', 'quest_card', 'ic_gift_quest_card', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('68', 'quilling_card', 'ic_gift_quilling_card', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('69', 'razor', 'ic_gift_razor', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('70', 'riding_card', 'ic_gift_riding_card', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('71', 'ridingtour_card', 'ic_gift_ridingtour_card', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('72', 'romantic_deinner', 'ic_gift_romantic_deinner', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('73', 'seat_covers', 'ic_gift_seat_covers', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('74', 'self_defense_card', 'ic_gift_self_defense_card', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('75', 'shavingkit', 'ic_gift_shavingkit', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('76', 'shop_card_m', 'ic_gift_shop_card_m', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('77', 'shopping_card', 'ic_gift_shopping_card', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('78', 'skateboard', 'ic_gift_skateboard', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('79', 'skewerkit', 'ic_gift_skewerkit', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('80', 'sleepwear_m', 'ic_gift_sleepwear_m', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('81', 'smartwatch', 'ic_gift_smartwatch', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('82', 'smoking_pipe', 'ic_gift_smoking_pipe', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('83', 'sneakers', 'ic_gift_sneakers', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('84', 'soccer_ticket', 'ic_gift_soccer_ticket', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('85', 'spa_card_1', 'ic_gift_spa_card_1', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('86', 'spa_card', 'ic_gift_spa_card', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('87', 'sport_stuff', 'ic_gift_sport_stuff', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('88', 'sushi_card', 'ic_gift_sushi_card', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('89', 'taepot', 'ic_gift_taepot', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('90', 'tennis_card', 'ic_gift_tennis_card', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('91', 'theatre_tickets', 'ic_gift_theatre_tickets', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('92', 'thermocup', 'ic_gift_thermocup', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('93', 'tonometr', 'ic_gift_tonometr', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('94', 'tools', 'ic_gift_tools', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('95', 'travel_case', 'ic_gift_travel_case', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('96', 'travel_tour_card', 'ic_gift_travel_tour_card', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('97', 'traveltour_tickets', 'ic_gift_traveltour_tickets', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('98', 'umbrella_m', 'ic_gift_umbrella_m', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('99', 'umbrella_w', 'ic_gift_umbrella_w', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('100', 'vocal_card', 'ic_gift_vocal_card', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('101', 'watch_m', 'ic_gift_watch_m', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('102', 'watch_w', 'ic_gift_watch_w', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('103', 'weekend_card', 'ic_gift_weekend_card', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('104', 'xbox', 'ic_gift_xbox', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert  into gifts (id, name, icon, caption) values ('105', 'yoga_card', 'ic_gift_yoga_card', 'Bacon ipsum dolor amet short ribs burgdoggen pork chop shoulder, pancetta picanha fatback hamburger');
insert into gift_targets values ('0', 'target_forwomen', 'forwomen', '0');
insert into targets_gift values (0, 0);
insert into targets_gift values (3, 0);
insert into targets_gift values (7, 0);
insert into targets_gift values (8, 0);
insert into targets_gift values (12, 0);
insert into targets_gift values (15, 0);
insert into targets_gift values (18, 0);
insert into targets_gift values (19, 0);
insert into targets_gift values (2, 0);
insert into targets_gift values (21, 0);
insert into targets_gift values (23, 0);
insert into targets_gift values (22, 0);
insert into targets_gift values (28, 0);
insert into targets_gift values (30, 0);
insert into targets_gift values (34, 0);
insert into targets_gift values (35, 0);
insert into targets_gift values (36, 0);
insert into targets_gift values (42, 0);
insert into targets_gift values (45, 0);
insert into targets_gift values (51, 0);
insert into targets_gift values (46, 0);
insert into targets_gift values (47, 0);
insert into targets_gift values (48, 0);
insert into targets_gift values (53, 0);
insert into targets_gift values (54, 0);
insert into targets_gift values (55, 0);
insert into targets_gift values (57, 0);
insert into targets_gift values (61, 0);
insert into targets_gift values (63, 0);
insert into targets_gift values (64, 0);
insert into targets_gift values (68, 0);
insert into targets_gift values (70, 0);
insert into targets_gift values (71, 0);
insert into targets_gift values (72, 0);
insert into targets_gift values (74, 0);
insert into targets_gift values (77, 0);
insert into targets_gift values (85, 0);
insert into targets_gift values (86, 0);
insert into targets_gift values (87, 0);
insert into targets_gift values (88, 0);
insert into targets_gift values (90, 0);
insert into targets_gift values (91, 0);
insert into targets_gift values (96, 0);
insert into targets_gift values (95, 0);
insert into targets_gift values (99, 0);
insert into targets_gift values (100, 0);
insert into targets_gift values (102, 0);
insert into targets_gift values (103, 0);
insert into targets_gift values (105, 0);
insert into gift_targets values ('1', 'target_formen', 'formen', '0');
insert into targets_gift values (0, 1);
insert into targets_gift values (3, 1);
insert into targets_gift values (1, 1);
insert into targets_gift values (4, 1);
insert into targets_gift values (5, 1);
insert into targets_gift values (6, 1);
insert into targets_gift values (8, 1);
insert into targets_gift values (9, 1);
insert into targets_gift values (10, 1);
insert into targets_gift values (11, 1);
insert into targets_gift values (12, 1);
insert into targets_gift values (13, 1);
insert into targets_gift values (14, 1);
insert into targets_gift values (16, 1);
insert into targets_gift values (17, 1);
insert into targets_gift values (18, 1);
insert into targets_gift values (20, 1);
insert into targets_gift values (21, 1);
insert into targets_gift values (25, 1);
insert into targets_gift values (26, 1);
insert into targets_gift values (27, 1);
insert into targets_gift values (28, 1);
insert into targets_gift values (29, 1);
insert into targets_gift values (30, 1);
insert into targets_gift values (31, 1);
insert into targets_gift values (32, 1);
insert into targets_gift values (33, 1);
insert into targets_gift values (35, 1);
insert into targets_gift values (37, 1);
insert into targets_gift values (38, 1);
insert into targets_gift values (39, 1);
insert into targets_gift values (41, 1);
insert into targets_gift values (43, 1);
insert into targets_gift values (44, 1);
insert into targets_gift values (49, 1);
insert into targets_gift values (50, 1);
insert into targets_gift values (51, 1);
insert into targets_gift values (52, 1);
insert into targets_gift values (54, 1);
insert into targets_gift values (56, 1);
insert into targets_gift values (58, 1);
insert into targets_gift values (59, 1);
insert into targets_gift values (60, 1);
insert into targets_gift values (62, 1);
insert into targets_gift values (66, 1);
insert into targets_gift values (67, 1);
insert into targets_gift values (69, 1);
insert into targets_gift values (73, 1);
insert into targets_gift values (75, 1);
insert into targets_gift values (76, 1);
insert into targets_gift values (78, 1);
insert into targets_gift values (79, 1);
insert into targets_gift values (80, 1);
insert into targets_gift values (81, 1);
insert into targets_gift values (82, 1);
insert into targets_gift values (83, 1);
insert into targets_gift values (84, 1);
insert into targets_gift values (87, 1);
insert into targets_gift values (90, 1);
insert into targets_gift values (92, 1);
insert into targets_gift values (93, 1);
insert into targets_gift values (94, 1);
insert into targets_gift values (95, 1);
insert into targets_gift values (97, 1);
insert into targets_gift values (98, 1);
insert into targets_gift values (101, 1);
insert into targets_gift values (103, 1);
insert into targets_gift values (104, 1);
insert into gift_targets values ('2', 'target_forchildren', 'forchildren', '0');
insert into targets_gift values (10, 2);
insert into targets_gift values (12, 2);
insert into targets_gift values (26, 2);
insert into targets_gift values (28, 2);
insert into targets_gift values (38, 2);
insert into targets_gift values (40, 2);
insert into targets_gift values (43, 2);
insert into targets_gift values (51, 2);
insert into targets_gift values (52, 2);
insert into targets_gift values (56, 2);
insert into targets_gift values (60, 2);
insert into targets_gift values (65, 2);
insert into targets_gift values (67, 2);
insert into targets_gift values (78, 2);
insert into targets_gift values (81, 2);
insert into targets_gift values (83, 2);
insert into targets_gift values (87, 2);
insert into targets_gift values (99, 2);
insert into targets_gift values (104, 2);
insert into gift_targets values ('3', 'target_hobby', 'hobby', '0');
insert into targets_gift values (1, 3);
insert into targets_gift values (0, 3);
insert into targets_gift values (3, 3);
insert into targets_gift values (8, 3);
insert into targets_gift values (30, 3);
insert into targets_gift values (42, 3);
insert into targets_gift values (45, 3);
insert into targets_gift values (46, 3);
insert into targets_gift values (53, 3);
insert into targets_gift values (61, 3);
insert into targets_gift values (64, 3);
insert into targets_gift values (68, 3);
insert into targets_gift values (70, 3);
insert into targets_gift values (72, 3);
insert into targets_gift values (77, 3);
insert into targets_gift values (85, 3);
insert into targets_gift values (86, 3);
insert into targets_gift values (88, 3);
insert into targets_gift values (90, 3);
insert into targets_gift values (91, 3);
insert into targets_gift values (96, 3);
insert into targets_gift values (100, 3);
insert into targets_gift values (105, 3);
insert into targets_gift values (2, 3);
insert into targets_gift values (5, 3);
insert into targets_gift values (10, 3);
insert into targets_gift values (11, 3);
insert into targets_gift values (12, 3);
insert into targets_gift values (13, 3);
insert into targets_gift values (14, 3);
insert into targets_gift values (16, 3);
insert into targets_gift values (18, 3);
insert into targets_gift values (21, 3);
insert into targets_gift values (24, 3);
insert into targets_gift values (25, 3);
insert into targets_gift values (26, 3);
insert into targets_gift values (28, 3);
insert into targets_gift values (29, 3);
insert into targets_gift values (31, 3);
insert into targets_gift values (32, 3);
insert into targets_gift values (37, 3);
insert into targets_gift values (38, 3);
insert into targets_gift values (39, 3);
insert into targets_gift values (40, 3);
insert into targets_gift values (43, 3);
insert into targets_gift values (44, 3);
insert into targets_gift values (49, 3);
insert into targets_gift values (62, 3);
insert into targets_gift values (65, 3);
insert into targets_gift values (67, 3);
insert into targets_gift values (76, 3);
insert into targets_gift values (78, 3);
insert into targets_gift values (79, 3);
insert into targets_gift values (81, 3);
insert into targets_gift values (82, 3);
insert into targets_gift values (84, 3);
insert into targets_gift values (87, 3);
insert into targets_gift values (94, 3);
insert into targets_gift values (95, 3);
insert into targets_gift values (97, 3);
insert into targets_gift values (101, 3);
insert into targets_gift values (103, 3);
insert into targets_gift values (104, 3);
insert into gift_targets values ('4', 'target_celebration', 'celebration', '0');
insert into targets_gift values (1, 4);
insert into targets_gift values (17, 4);
insert into targets_gift values (18, 4);
insert into targets_gift values (75, 4);
insert into targets_gift values (84, 4);
insert into targets_gift values (97, 4);
insert into targets_gift values (103, 4);
insert into targets_gift values (36, 4);
insert into targets_gift values (46, 4);
insert into targets_gift values (72, 4);
insert into targets_gift values (86, 4);
insert into targets_gift values (87, 4);
insert into targets_gift values (88, 4);
insert into targets_gift values (91, 4);
insert into gift_targets values ('5', 'target_profession', 'profession', '0');
insert into targets_gift values (4, 5);
insert into targets_gift values (6, 5);
insert into targets_gift values (12, 5);
insert into targets_gift values (17, 5);
insert into targets_gift values (62, 5);
insert into targets_gift values (73, 5);
insert into targets_gift values (95, 5);
insert into targets_gift values (102, 5);
insert into targets_gift values (101, 5);
insert into gift_targets values ('6', 'target_housewife', 'housewife', '1');
insert into targets_gift values (15, 6);
insert into targets_gift values (19, 6);
insert into targets_gift values (23, 6);
insert into targets_gift values (22, 6);
insert into targets_gift values (34, 6);
insert into targets_gift values (47, 6);
insert into targets_gift values (48, 6);
insert into targets_gift values (55, 6);
insert into targets_gift values (53, 6);
insert into targets_gift values (54, 6);
insert into targets_gift values (57, 6);
insert into targets_gift values (77, 6);
insert into targets_gift values (85, 6);
insert into targets_gift values (89, 6);
insert into targets_gift values (91, 6);
insert into targets_gift values (99, 6);
insert into targets_gift values (2, 6);
insert into targets_gift values (105, 6);
insert into gift_targets values ('7', 'target_photo', 'photo', '1');
insert into targets_gift values (55, 7);
insert into targets_gift values (14, 7);
insert into targets_gift values (29, 7);
insert into targets_gift values (33, 7);
insert into targets_gift values (38, 7);
insert into targets_gift values (51, 7);
insert into targets_gift values (60, 7);
insert into targets_gift values (62, 7);
insert into gift_targets values ('8', 'target_music', 'music', '1');
insert into targets_gift values (26, 8);
insert into targets_gift values (33, 8);
insert into targets_gift values (40, 8);
insert into targets_gift values (43, 8);
insert into targets_gift values (60, 8);
insert into gift_targets values ('9', 'target_work', 'work', '1');
insert into targets_gift values (7, 9);
insert into targets_gift values (61, 9);
insert into targets_gift values (99, 9);
insert into targets_gift values (102, 9);
insert into targets_gift values (6, 9);
insert into targets_gift values (9, 9);
insert into targets_gift values (17, 9);
insert into targets_gift values (20, 9);
insert into targets_gift values (21, 9);
insert into targets_gift values (27, 9);
insert into targets_gift values (38, 9);
insert into targets_gift values (41, 9);
insert into targets_gift values (50, 9);
insert into targets_gift values (51, 9);
insert into targets_gift values (52, 9);
insert into targets_gift values (58, 9);
insert into targets_gift values (60, 9);
insert into targets_gift values (66, 9);
insert into targets_gift values (69, 9);
insert into targets_gift values (75, 9);
insert into targets_gift values (81, 9);
insert into targets_gift values (92, 9);
insert into targets_gift values (93, 9);
insert into targets_gift values (98, 9);
insert into targets_gift values (101, 9);
insert into gift_targets values ('10', 'target_creative', 'creative', '1');
insert into targets_gift values (0, 10);
insert into targets_gift values (3, 10);
insert into targets_gift values (14, 10);
insert into targets_gift values (18, 10);
insert into targets_gift values (21, 10);
insert into targets_gift values (26, 10);
insert into targets_gift values (40, 10);
insert into targets_gift values (43, 10);
insert into targets_gift values (51, 10);
insert into targets_gift values (62, 10);
insert into targets_gift values (64, 10);
insert into targets_gift values (67, 10);
insert into targets_gift values (68, 10);
insert into targets_gift values (100, 10);
insert into gift_targets values ('11', 'target_cooking', 'cooking', '1');
insert into targets_gift values (15, 11);
insert into targets_gift values (19, 11);
insert into targets_gift values (23, 11);
insert into targets_gift values (22, 11);
insert into targets_gift values (34, 11);
insert into targets_gift values (48, 11);
insert into targets_gift values (57, 11);
insert into targets_gift values (88, 11);
insert into targets_gift values (89, 11);
insert into targets_gift values (39, 11);
insert into targets_gift values (79, 11);
insert into targets_gift values (92, 11);
insert into gift_targets values ('12', 'target_driver', 'driver', '1');
insert into targets_gift values (4, 12);
insert into targets_gift values (25, 12);
insert into targets_gift values (30, 12);
insert into targets_gift values (38, 12);
insert into targets_gift values (44, 12);
insert into targets_gift values (54, 12);
insert into targets_gift values (61, 12);              insert into targets_gift values (60, 12);
insert into targets_gift values (73, 12);
insert into targets_gift values (94, 12);
insert into targets_gift values (95, 12);
insert into gift_targets values ('13', 'target_fisher', 'fisher', '1');
insert into targets_gift values (1, 13);
insert into targets_gift values (6, 13);
insert into targets_gift values (9, 13);
insert into targets_gift values (12, 13);
insert into targets_gift values (17, 13);
insert into targets_gift values (31, 13);
insert into targets_gift values (32, 13);
insert into targets_gift values (38, 13);
insert into targets_gift values (39, 13);
insert into targets_gift values (57, 13);
insert into gift_targets values ('14', 'target_hunter', 'hunter', '1');
insert into targets_gift values (1, 14);
insert into targets_gift values (6, 14);
insert into targets_gift values (9, 14);
insert into targets_gift values (12, 14);
insert into targets_gift values (17, 14);
insert into targets_gift values (38, 14);
insert into targets_gift values (39, 14);
insert into targets_gift values (57, 14);
insert into targets_gift values (79, 14);
insert into gift_targets values ('15', 'target_itperson', 'itperson', '1');
insert into targets_gift values (21, 15);
insert into targets_gift values (28, 15);
insert into targets_gift values (33, 15);
insert into targets_gift values (43, 15);
insert into targets_gift values (51, 15);
insert into targets_gift values (60, 15);
insert into targets_gift values (61, 15);
insert into targets_gift values (65, 15);
insert into targets_gift values (81, 15);
insert into targets_gift values (83, 15);
insert into targets_gift values (92, 15);
insert into targets_gift values (104, 15);
insert into gift_targets values ('16', 'target_sport', 'sport', '1');
insert into targets_gift values (42, 16);
insert into targets_gift values (45, 16);
insert into targets_gift values (53, 16);
insert into targets_gift values (70, 16);
insert into targets_gift values (74, 16);
insert into targets_gift values (90, 16);
insert into targets_gift values (105, 16);
insert into targets_gift values (17, 16);
insert into targets_gift values (20, 16);
insert into targets_gift values (41, 16);
insert into targets_gift values (44, 16);
insert into targets_gift values (49, 16);
insert into targets_gift values (58, 16);
insert into targets_gift values (75, 16);
insert into targets_gift values (81, 16);
insert into targets_gift values (83, 16);
insert into targets_gift values (84, 16);
insert into targets_gift values (87, 16);
insert into targets_gift values (92, 16);
insert into targets_gift values (93, 16);
insert into gift_targets values ('17', 'target_coffe', 'coffe', '1');
insert into targets_gift values (15, 17);
insert into targets_gift values (16, 17);
insert into targets_gift values (19, 17);
insert into targets_gift values (89, 17);
insert into targets_gift values (76, 17);
insert into targets_gift values (82, 17);
insert into targets_gift values (92, 17);
insert into gift_targets values ('18', 'target_wine', 'wine', '1');
insert into targets_gift values (1, 18);
insert into targets_gift values (16, 18);
insert into targets_gift values (72, 18);
insert into targets_gift values (77, 18);
insert into targets_gift values (23, 18);
insert into gift_targets values ('19', 'target_book', 'book', '1');
insert into targets_gift values (12, 19);
insert into targets_gift values (21, 19);
insert into targets_gift values (28, 19);
insert into targets_gift values (43, 19);
insert into targets_gift values (44, 19);
insert into targets_gift values (76, 19);
insert into targets_gift values (2, 19);
insert into gift_targets values ('20', 'target_traveling', 'traveling', '1');
insert into targets_gift values (7, 20);
insert into targets_gift values (8, 20);
insert into targets_gift values (61, 20);
insert into targets_gift values (63, 20);
insert into targets_gift values (71, 20);
insert into targets_gift values (96, 20);
insert into targets_gift values (99, 20);
insert into targets_gift values (102, 20);
insert into targets_gift values (6, 20);
insert into targets_gift values (10, 20);
insert into targets_gift values (14, 20);
insert into targets_gift values (29, 20);
insert into targets_gift values (38, 20);
insert into targets_gift values (43, 20);
insert into targets_gift values (50, 20);
insert into targets_gift values (52, 20);
insert into targets_gift values (83, 20);
insert into targets_gift values (92, 20);
insert into targets_gift values (95, 20);
insert into targets_gift values (97, 20);
insert into targets_gift values (98, 20);
insert into gift_targets values ('21', 'target_game', 'game', '1');
insert into targets_gift values (43, 21);
insert into targets_gift values (51, 21);
insert into targets_gift values (60, 21);
insert into targets_gift values (65, 21);
insert into targets_gift values (67, 21);
insert into targets_gift values (104, 21);
insert into gift_targets values ('22', 'target_film', 'film', '1');
insert into targets_gift values (0, 22);
insert into targets_gift values (43, 22);
insert into targets_gift values (51, 22);
insert into gift_targets values ('23', 'target_mother', 'mother', '2');
insert into targets_gift values (7, 23);
insert into targets_gift values (12, 23);
insert into targets_gift values (15, 23);
insert into targets_gift values (19, 23);
insert into targets_gift values (21, 23);
insert into targets_gift values (28, 23);
insert into targets_gift values (23, 23);
insert into targets_gift values (22, 23);
insert into targets_gift values (34, 23);
insert into targets_gift values (35, 23);
insert into targets_gift values (45, 23);
insert into targets_gift values (47, 23);
insert into targets_gift values (48, 23);
insert into targets_gift values (53, 23);
insert into targets_gift values (55, 23);
insert into targets_gift values (57, 23);
insert into targets_gift values (63, 23);
insert into targets_gift values (77, 23);
insert into targets_gift values (85, 23);
insert into targets_gift values (89, 23);
insert into targets_gift values (91, 23);
insert into targets_gift values (96, 23);
insert into targets_gift values (95, 23);
insert into targets_gift values (93, 23);
insert into targets_gift values (99, 23);
insert into targets_gift values (102, 23);
insert into targets_gift values (103, 23);
insert into targets_gift values (2, 23);
insert into gift_targets values ('24', 'target_mother_in_low', 'mother_in_low', '2');
insert into targets_gift values (7, 24);
insert into targets_gift values (12, 24);
insert into targets_gift values (15, 24);
insert into targets_gift values (19, 24);
insert into targets_gift values (23, 24);
insert into targets_gift values (22, 24);
insert into targets_gift values (28, 24);
insert into targets_gift values (34, 24);
insert into targets_gift values (35, 24);
insert into targets_gift values (45, 24);
insert into targets_gift values (47, 24);
insert into targets_gift values (48, 24);
insert into targets_gift values (53, 24);
insert into targets_gift values (55, 24);
insert into targets_gift values (57, 24);
insert into targets_gift values (63, 24);
insert into targets_gift values (77, 24);
insert into targets_gift values (85, 24);
insert into targets_gift values (89, 24);
insert into targets_gift values (91, 24);
insert into targets_gift values (96, 24);
insert into targets_gift values (95, 24);
insert into targets_gift values (99, 24);
insert into targets_gift values (102, 24);
insert into targets_gift values (103, 24);
insert into targets_gift values (2, 24);
insert into gift_targets values ('25', 'target_grandmother', 'grandmother', '2');
insert into targets_gift values (12, 25);
insert into targets_gift values (15, 25);
insert into targets_gift values (19, 25);
insert into targets_gift values (23, 25);
insert into targets_gift values (22, 25);
insert into targets_gift values (34, 25);
insert into targets_gift values (35, 25);
insert into targets_gift values (45, 25);
insert into targets_gift values (48, 25);
insert into targets_gift values (53, 25);
insert into targets_gift values (54, 25);
insert into targets_gift values (57, 25);
insert into targets_gift values (63, 25);
insert into targets_gift values (77, 25);
insert into targets_gift values (89, 25);
insert into targets_gift values (91, 25);
insert into targets_gift values (93, 25);
insert into targets_gift values (99, 25);
insert into targets_gift values (2, 25);
insert into gift_targets values ('26', 'target_wife', 'wife', '2');
insert into targets_gift values (12, 26);
insert into targets_gift values (0, 26);
insert into targets_gift values (3, 26);
insert into targets_gift values (7, 26);
insert into targets_gift values (8, 26);
insert into targets_gift values (14, 26);
insert into targets_gift values (15, 26);
insert into targets_gift values (18, 26);
insert into targets_gift values (19, 26);
insert into targets_gift values (21, 26);
insert into targets_gift values (23, 26);
insert into targets_gift values (22, 26);
insert into targets_gift values (28, 26);
insert into targets_gift values (34, 26);
insert into targets_gift values (36, 26);
insert into targets_gift values (42, 26);
insert into targets_gift values (46, 26);
insert into targets_gift values (47, 26);
insert into targets_gift values (51, 26);
insert into targets_gift values (53, 26);
insert into targets_gift values (55, 26);
insert into targets_gift values (61, 26);
insert into targets_gift values (64, 26);
insert into targets_gift values (68, 26);
insert into targets_gift values (70, 26);
insert into targets_gift values (72, 26);
insert into targets_gift values (74, 26);
insert into targets_gift values (77, 26);
insert into targets_gift values (86, 26);
insert into targets_gift values (88, 26);
insert into targets_gift values (90, 26);
insert into targets_gift values (91, 26);
insert into targets_gift values (96, 26);
insert into targets_gift values (95, 26);
insert into targets_gift values (100, 26);
insert into targets_gift values (103, 26);
insert into targets_gift values (105, 26);
insert into gift_targets values ('27', 'target_girlfriend', 'girlfriend', '2');
insert into targets_gift values (12, 27);
insert into targets_gift values (0, 27);
insert into targets_gift values (3, 27);
insert into targets_gift values (7, 27);
insert into targets_gift values (8, 27);
insert into targets_gift values (14, 27);
insert into targets_gift values (18, 27);
insert into targets_gift values (21, 27);
insert into targets_gift values (28, 27);
insert into targets_gift values (30, 27);
insert into targets_gift values (36, 27);
insert into targets_gift values (42, 27);
insert into targets_gift values (46, 27);
insert into targets_gift values (47, 27);
insert into targets_gift values (53, 27);
insert into targets_gift values (61, 27);
insert into targets_gift values (68, 27);
insert into targets_gift values (71, 27);
insert into targets_gift values (72, 27);
insert into targets_gift values (74, 27);
insert into targets_gift values (77, 27);
insert into targets_gift values (86, 27);
insert into targets_gift values (87, 27);
insert into targets_gift values (88, 27);
insert into targets_gift values (91, 27);
insert into targets_gift values (96, 27);
insert into targets_gift values (100, 27);
insert into targets_gift values (102, 27);
insert into targets_gift values (103, 27);
insert into targets_gift values (105, 27);
insert into gift_targets values ('28', 'target_sister', 'sister', '2');
insert into targets_gift values (12, 28);
insert into targets_gift values (0, 28);
insert into targets_gift values (3, 28);
insert into targets_gift values (7, 28);
insert into targets_gift values (8, 28);
insert into targets_gift values (14, 28);
insert into targets_gift values (18, 28);
insert into targets_gift values (19, 28);
insert into targets_gift values (21, 28);
insert into targets_gift values (28, 28);
insert into targets_gift values (30, 28);
insert into targets_gift values (42, 28);
insert into targets_gift values (46, 28);
insert into targets_gift values (47, 28);
insert into targets_gift values (51, 28);
insert into targets_gift values (53, 28);
insert into targets_gift values (61, 28);
insert into targets_gift values (68, 28);
insert into targets_gift values (71, 28);
insert into targets_gift values (74, 28);
insert into targets_gift values (77, 28);
insert into targets_gift values (87, 28);
insert into targets_gift values (88, 28);
insert into targets_gift values (91, 28);
insert into targets_gift values (96, 28);
insert into targets_gift values (95, 28);
insert into targets_gift values (100, 28);
insert into targets_gift values (102, 28);
insert into targets_gift values (103, 28);
insert into targets_gift values (105, 28);
insert into gift_targets values ('29', 'target_daughterinlow', 'daughterinlow', '2');
insert into targets_gift values (12, 29);
insert into targets_gift values (0, 29);
insert into targets_gift values (15, 29);
insert into targets_gift values (18, 29);
insert into targets_gift values (19, 29);
insert into targets_gift values (2, 29);
insert into targets_gift values (23, 29);
insert into targets_gift values (22, 29);
insert into targets_gift values (28, 29);
insert into targets_gift values (34, 29);
insert into targets_gift values (47, 29);
insert into targets_gift values (48, 29);
insert into targets_gift values (53, 29);
insert into targets_gift values (55, 29);
insert into targets_gift values (57, 29);
insert into targets_gift values (61, 29);
insert into targets_gift values (63, 29);
insert into targets_gift values (64, 29);
insert into targets_gift values (68, 29);
insert into targets_gift values (70, 29);
insert into targets_gift values (71, 29);
insert into targets_gift values (77, 29);
insert into targets_gift values (86, 29);
insert into targets_gift values (89, 29);
insert into targets_gift values (90, 29);
insert into targets_gift values (91, 29);
insert into targets_gift values (96, 29);
insert into targets_gift values (95, 29);
insert into targets_gift values (99, 29);
insert into targets_gift values (100, 29);
insert into targets_gift values (103, 29);
insert into targets_gift values (102, 29);
insert into gift_targets values ('30', 'target_daughter', 'daughter', '2');
insert into targets_gift values (12, 30);
insert into targets_gift values (0, 30);
insert into targets_gift values (3, 30);
insert into targets_gift values (7, 30);
insert into targets_gift values (14, 30);
insert into targets_gift values (19, 30);
insert into targets_gift values (2, 30);
insert into targets_gift values (21, 30);
insert into targets_gift values (28, 30);
insert into targets_gift values (42, 30);
insert into targets_gift values (47, 30);
insert into targets_gift values (51, 30);
insert into targets_gift values (55, 30);
insert into targets_gift values (61, 30);
insert into targets_gift values (63, 30);
insert into targets_gift values (64, 30);
insert into targets_gift values (68, 30);
insert into targets_gift values (71, 30);
insert into targets_gift values (74, 30);
insert into targets_gift values (77, 30);
insert into targets_gift values (86, 30);
insert into targets_gift values (87, 30);
insert into targets_gift values (89, 30);
insert into targets_gift values (90, 30);
insert into targets_gift values (91, 30);
insert into targets_gift values (96, 30);
insert into targets_gift values (95, 30);
insert into targets_gift values (99, 30);
insert into targets_gift values (100, 30);
insert into targets_gift values (102, 30);
insert into targets_gift values (105, 30);
insert into gift_targets values ('31', 'target_aunt', 'aunt', '2');
insert into targets_gift values (12, 31);
insert into targets_gift values (7, 31);
insert into targets_gift values (15, 31);
insert into targets_gift values (19, 31);
insert into targets_gift values (2, 31);
insert into targets_gift values (23, 31);
insert into targets_gift values (22, 31);
insert into targets_gift values (28, 31);
insert into targets_gift values (34, 31);
insert into targets_gift values (42, 31);
insert into targets_gift values (45, 31);
insert into targets_gift values (46, 31);
insert into targets_gift values (47, 31);
insert into targets_gift values (48, 31);
insert into targets_gift values (53, 31);
insert into targets_gift values (55, 31);
insert into targets_gift values (57, 31);
insert into targets_gift values (61, 31);
insert into targets_gift values (63, 31);
insert into targets_gift values (64, 31);
insert into targets_gift values (71, 31);
insert into targets_gift values (74, 31);
insert into targets_gift values (77, 31);
insert into targets_gift values (86, 31);
insert into targets_gift values (88, 31);
insert into targets_gift values (89, 31);
insert into targets_gift values (90, 31);
insert into targets_gift values (91, 31);
insert into targets_gift values (96, 31);
insert into targets_gift values (95, 31);
insert into targets_gift values (99, 31);
insert into targets_gift values (100, 31);
insert into targets_gift values (102, 31);
insert into targets_gift values (105, 31);
insert into gift_targets values ('32', 'target_friend', 'friend', '2');
insert into targets_gift values (12, 32);
insert into targets_gift values (0, 32);
insert into targets_gift values (3, 32);
insert into targets_gift values (7, 32);
insert into targets_gift values (8, 32);
insert into targets_gift values (14, 32);
insert into targets_gift values (15, 32);
insert into targets_gift values (18, 32);
insert into targets_gift values (19, 32);
insert into targets_gift values (2, 32);
insert into targets_gift values (21, 32);
insert into targets_gift values (28, 32);
insert into targets_gift values (23, 32);
insert into targets_gift values (22, 32);
insert into targets_gift values (30, 32);
insert into targets_gift values (34, 32);
insert into targets_gift values (42, 32);
insert into targets_gift values (45, 32);
insert into targets_gift values (46, 32);
insert into targets_gift values (47, 32);
insert into targets_gift values (48, 32);
insert into targets_gift values (53, 32);
insert into targets_gift values (55, 32);
insert into targets_gift values (57, 32);
insert into targets_gift values (61, 32);
insert into targets_gift values (63, 32);
insert into targets_gift values (64, 32);
insert into targets_gift values (68, 32);
insert into targets_gift values (70, 32);
insert into targets_gift values (71, 32);
insert into targets_gift values (74, 32);
insert into targets_gift values (77, 32);
insert into targets_gift values (86, 32);
insert into targets_gift values (87, 32);
insert into targets_gift values (88, 32);
insert into targets_gift values (89, 32);
insert into targets_gift values (90, 32);
insert into targets_gift values (91, 32);
insert into targets_gift values (96, 32);
insert into targets_gift values (95, 32);
insert into targets_gift values (99, 32);
insert into targets_gift values (100, 32);
insert into targets_gift values (102, 32);
insert into targets_gift values (103, 32);
insert into targets_gift values (105, 32);
insert into gift_targets values ('33', 'target_boyfriend', 'boyfriend', '3');
insert into targets_gift values (0, 33);
insert into targets_gift values (3, 33);
insert into targets_gift values (4, 33);
insert into targets_gift values (5, 33);
insert into targets_gift values (6, 33);
insert into targets_gift values (8, 33);
insert into targets_gift values (9, 33);
insert into targets_gift values (10, 33);
insert into targets_gift values (11, 33);
insert into targets_gift values (12, 33);
insert into targets_gift values (13, 33);
insert into targets_gift values (14, 33);
insert into targets_gift values (18, 33);
insert into targets_gift values (20, 33);
insert into targets_gift values (25, 33);
insert into targets_gift values (26, 33);
insert into targets_gift values (28, 33);
insert into targets_gift values (29, 33);
insert into targets_gift values (30, 33);
insert into targets_gift values (37, 33);
insert into targets_gift values (38, 33);
insert into targets_gift values (39, 33);
insert into targets_gift values (41, 33);
insert into targets_gift values (43, 33);
insert into targets_gift values (49, 33);
insert into targets_gift values (51, 33);
insert into targets_gift values (52, 33);
insert into targets_gift values (59, 33);
insert into targets_gift values (60, 33);
insert into targets_gift values (62, 33);
insert into targets_gift values (65, 33);
insert into targets_gift values (66, 33);
insert into targets_gift values (67, 33);
insert into targets_gift values (75, 33);
insert into targets_gift values (76, 33);
insert into targets_gift values (78, 33);
insert into targets_gift values (81, 33);
insert into targets_gift values (83, 33);
insert into targets_gift values (84, 33);
insert into targets_gift values (87, 33);
insert into targets_gift values (90, 33);
insert into targets_gift values (97, 33);
insert into targets_gift values (98, 33);
insert into targets_gift values (101, 33);
insert into targets_gift values (103, 33);
insert into targets_gift values (104, 33);
insert into gift_targets values ('34', 'target_husband', 'husband', '3');
insert into targets_gift values (1, 34);
insert into targets_gift values (4, 34);
insert into targets_gift values (5, 34);
insert into targets_gift values (6, 34);
insert into targets_gift values (8, 34);
insert into targets_gift values (9, 34);
insert into targets_gift values (10, 34);
insert into targets_gift values (11, 34);
insert into targets_gift values (12, 34);
insert into targets_gift values (13, 34);
insert into targets_gift values (14, 34);
insert into targets_gift values (16, 34);
insert into targets_gift values (17, 34);
insert into targets_gift values (18, 34);
insert into targets_gift values (20, 34);
insert into targets_gift values (21, 34);
insert into targets_gift values (26, 34);
insert into targets_gift values (27, 34);
insert into targets_gift values (28, 34);
insert into targets_gift values (29, 34);
insert into targets_gift values (30, 34);
insert into targets_gift values (31, 34);
insert into targets_gift values (32, 34);
insert into targets_gift values (33, 34);
insert into targets_gift values (38, 34);
insert into targets_gift values (39, 34);
insert into targets_gift values (41, 34);
insert into targets_gift values (43, 34);
insert into targets_gift values (44, 34);
insert into targets_gift values (50, 34);
insert into targets_gift values (51, 34);
insert into targets_gift values (52, 34);
insert into targets_gift values (54, 34);
insert into targets_gift values (58, 34);
insert into targets_gift values (60, 34);
insert into targets_gift values (62, 34);
insert into targets_gift values (66, 34);
insert into targets_gift values (67, 34);
insert into targets_gift values (69, 34);
insert into targets_gift values (73, 34);
insert into targets_gift values (75, 34);
insert into targets_gift values (76, 34);
insert into targets_gift values (79, 34);
insert into targets_gift values (80, 34);
insert into targets_gift values (81, 34);
insert into targets_gift values (82, 34);
insert into targets_gift values (84, 34);
insert into targets_gift values (87, 34);
insert into targets_gift values (90, 34);
insert into targets_gift values (92, 34);
insert into targets_gift values (95, 34);
insert into targets_gift values (97, 34);
insert into targets_gift values (98, 34);
insert into targets_gift values (101, 34);
insert into targets_gift values (103, 34);
insert into targets_gift values (104, 34);
insert into gift_targets values ('35', 'target_brother', 'brother', '3');
insert into targets_gift values (0, 35);
insert into targets_gift values (3, 35);
insert into targets_gift values (4, 35);
insert into targets_gift values (5, 35);
insert into targets_gift values (6, 35);
insert into targets_gift values (9, 35);
insert into targets_gift values (10, 35);
insert into targets_gift values (11, 35);
insert into targets_gift values (12, 35);
insert into targets_gift values (13, 35);
insert into targets_gift values (14, 35);
insert into targets_gift values (17, 35);
insert into targets_gift values (18, 35);
insert into targets_gift values (20, 35);
insert into targets_gift values (21, 35);
insert into targets_gift values (25, 35);
insert into targets_gift values (26, 35);
insert into targets_gift values (27, 35);
insert into targets_gift values (28, 35);
insert into targets_gift values (29, 35);
insert into targets_gift values (30, 35);
insert into targets_gift values (31, 35);
insert into targets_gift values (32, 35);
insert into targets_gift values (37, 35);
insert into targets_gift values (38, 35);
insert into targets_gift values (39, 35);
insert into targets_gift values (41, 35);
insert into targets_gift values (43, 35);
insert into targets_gift values (44, 35);
insert into targets_gift values (49, 35);
insert into targets_gift values (50, 35);
insert into targets_gift values (51, 35);
insert into targets_gift values (52, 35);
insert into targets_gift values (54, 35);
insert into targets_gift values (56, 35);
insert into targets_gift values (60, 35);
insert into targets_gift values (62, 35);
insert into targets_gift values (66, 35);
insert into targets_gift values (67, 35);
insert into targets_gift values (73, 35);
insert into targets_gift values (75, 35);
insert into targets_gift values (76, 35);
insert into targets_gift values (78, 35);
insert into targets_gift values (79, 35);
insert into targets_gift values (81, 35);
insert into targets_gift values (83, 35);
insert into targets_gift values (84, 35);
insert into targets_gift values (87, 35);
insert into targets_gift values (90, 35);
insert into targets_gift values (92, 35);
insert into targets_gift values (94, 35);
insert into targets_gift values (95, 35);
insert into targets_gift values (97, 35);
insert into targets_gift values (101, 35);
insert into targets_gift values (103, 35);
insert into targets_gift values (104, 35);
insert into gift_targets values ('36', 'target_soninlow', 'soninlow', '3');
insert into targets_gift values (1, 36);
insert into targets_gift values (4, 36);
insert into targets_gift values (6, 36);
insert into targets_gift values (9, 36);
insert into targets_gift values (10, 36);
insert into targets_gift values (11, 36);
insert into targets_gift values (12, 36);
insert into targets_gift values (13, 36);
insert into targets_gift values (14, 36);
insert into targets_gift values (17, 36);
insert into targets_gift values (18, 36);
insert into targets_gift values (20, 36);
insert into targets_gift values (21, 36);
insert into targets_gift values (25, 36);
insert into targets_gift values (27, 36);
insert into targets_gift values (28, 36);
insert into targets_gift values (32, 36);
insert into targets_gift values (38, 36);
insert into targets_gift values (39, 36);
insert into targets_gift values (41, 36);
insert into targets_gift values (43, 36);
insert into targets_gift values (44, 36);
insert into targets_gift values (50, 36);
insert into targets_gift values (51, 36);
insert into targets_gift values (52, 36);
insert into targets_gift values (54, 36);
insert into targets_gift values (58, 36);
insert into targets_gift values (60, 36);
insert into targets_gift values (62, 36);
insert into targets_gift values (66, 36);
insert into targets_gift values (75, 36);
insert into targets_gift values (76, 36);
insert into targets_gift values (79, 36);
insert into targets_gift values (81, 36);
insert into targets_gift values (84, 36);
insert into targets_gift values (87, 36);
insert into targets_gift values (90, 36);
insert into targets_gift values (92, 36);
insert into targets_gift values (95, 36);
insert into targets_gift values (97, 36);
insert into targets_gift values (98, 36);
insert into targets_gift values (101, 36);
insert into targets_gift values (103, 36);
insert into gift_targets values ('37', 'target_grandfather', 'grandfather', '3');
insert into targets_gift values (1, 37);
insert into targets_gift values (4, 37);
insert into targets_gift values (5, 37);
insert into targets_gift values (6, 37);
insert into targets_gift values (9, 37);
insert into targets_gift values (11, 37);
insert into targets_gift values (12, 37);
insert into targets_gift values (20, 37);
insert into targets_gift values (27, 37);
insert into targets_gift values (28, 37);
insert into targets_gift values (31, 37);
insert into targets_gift values (32, 37);
insert into targets_gift values (35, 37);
insert into targets_gift values (38, 37);
insert into targets_gift values (39, 37);
insert into targets_gift values (44, 37);
insert into targets_gift values (50, 37);
insert into targets_gift values (51, 37);
insert into targets_gift values (54, 37);
insert into targets_gift values (58, 37);
insert into targets_gift values (60, 37);
insert into targets_gift values (66, 37);
insert into targets_gift values (69, 37);
insert into targets_gift values (73, 37);
insert into targets_gift values (75, 37);
insert into targets_gift values (79, 37);
insert into targets_gift values (80, 37);
insert into targets_gift values (82, 37);
insert into targets_gift values (84, 37);
insert into targets_gift values (92, 37);
insert into targets_gift values (93, 37);
insert into targets_gift values (94, 37);
insert into targets_gift values (98, 37);
insert into targets_gift values (101, 37);
insert into targets_gift values (103, 37);
insert into gift_targets values ('38', 'target_father', 'father', '3');
insert into targets_gift values (1, 38);
insert into targets_gift values (4, 38);
insert into targets_gift values (5, 38);
insert into targets_gift values (6, 38);
insert into targets_gift values (9, 38);
insert into targets_gift values (10, 38);
insert into targets_gift values (11, 38);
insert into targets_gift values (12, 38);
insert into targets_gift values (14, 38);
insert into targets_gift values (16, 38);
insert into targets_gift values (17, 38);
insert into targets_gift values (20, 38);
insert into targets_gift values (21, 38);
insert into targets_gift values (27, 38);
insert into targets_gift values (28, 38);
insert into targets_gift values (29, 38);
insert into targets_gift values (31, 38);
insert into targets_gift values (32, 38);
insert into targets_gift values (33, 38);
insert into targets_gift values (35, 38);
insert into targets_gift values (38, 38);
insert into targets_gift values (39, 38);
insert into targets_gift values (44, 38);
insert into targets_gift values (50, 38);
insert into targets_gift values (51, 38);
insert into targets_gift values (52, 38);
insert into targets_gift values (54, 38);
insert into targets_gift values (58, 38);
insert into targets_gift values (60, 38);
insert into targets_gift values (62, 38);
insert into targets_gift values (66, 38);
insert into targets_gift values (69, 38);
insert into targets_gift values (73, 38);
insert into targets_gift values (75, 38);
insert into targets_gift values (76, 38);
insert into targets_gift values (79, 38);
insert into targets_gift values (80, 38);
insert into targets_gift values (81, 38);
insert into targets_gift values (82, 38);
insert into targets_gift values (84, 38);
insert into targets_gift values (90, 38);
insert into targets_gift values (92, 38);
insert into targets_gift values (93, 38);
insert into targets_gift values (94, 38);
insert into targets_gift values (95, 38);
insert into targets_gift values (97, 38);
insert into targets_gift values (98, 38);
insert into targets_gift values (101, 38);
insert into targets_gift values (103, 38);
insert into gift_targets values ('39', 'target_son', 'son', '3');
insert into targets_gift values (0, 39);
insert into targets_gift values (3, 39);
insert into targets_gift values (6, 39);
insert into targets_gift values (8, 39);
insert into targets_gift values (9, 39);
insert into targets_gift values (10, 39);
insert into targets_gift values (12, 39);
insert into targets_gift values (13, 39);
insert into targets_gift values (14, 39);
insert into targets_gift values (17, 39);
insert into targets_gift values (18, 39);
insert into targets_gift values (20, 39);
insert into targets_gift values (25, 39);
insert into targets_gift values (26, 39);
insert into targets_gift values (28, 39);
insert into targets_gift values (29, 39);
insert into targets_gift values (30, 39);
insert into targets_gift values (33, 39);
insert into targets_gift values (37, 39);
insert into targets_gift values (38, 39);
insert into targets_gift values (41, 39);
insert into targets_gift values (43, 39);
insert into targets_gift values (49, 39);
insert into targets_gift values (51, 39);
insert into targets_gift values (52, 39);
insert into targets_gift values (56, 39);
insert into targets_gift values (59, 39);
insert into targets_gift values (60, 39);
insert into targets_gift values (62, 39);
insert into targets_gift values (66, 39);
insert into targets_gift values (67, 39);
insert into targets_gift values (73, 39);
insert into targets_gift values (75, 39);
insert into targets_gift values (76, 39);
insert into targets_gift values (78, 39);
insert into targets_gift values (80, 39);
insert into targets_gift values (81, 39);
insert into targets_gift values (83, 39);
insert into targets_gift values (84, 39);
insert into targets_gift values (87, 39);
insert into targets_gift values (90, 39);
insert into targets_gift values (92, 39);
insert into targets_gift values (98, 39);
insert into targets_gift values (101, 39);
insert into targets_gift values (104, 39);
insert into gift_targets values ('40', 'target_uncle', 'uncle', '3');
insert into targets_gift values (1, 40);
insert into targets_gift values (4, 40);
insert into targets_gift values (5, 40);
insert into targets_gift values (6, 40);
insert into targets_gift values (9, 40);
insert into targets_gift values (10, 40);
insert into targets_gift values (11, 40);
insert into targets_gift values (12, 40);
insert into targets_gift values (14, 40);
insert into targets_gift values (16, 40);
insert into targets_gift values (17, 40);
insert into targets_gift values (20, 40);
insert into targets_gift values (21, 40);
insert into targets_gift values (27, 40);
insert into targets_gift values (28, 40);
insert into targets_gift values (29, 40);
insert into targets_gift values (31, 40);
insert into targets_gift values (32, 40);
insert into targets_gift values (33, 40);
insert into targets_gift values (35, 40);
insert into targets_gift values (38, 40);
insert into targets_gift values (39, 40);
insert into targets_gift values (44, 40);
insert into targets_gift values (50, 40);
insert into targets_gift values (51, 40);
insert into targets_gift values (52, 40);
insert into targets_gift values (54, 40);
insert into targets_gift values (58, 40);
insert into targets_gift values (60, 40);
insert into targets_gift values (62, 40);
insert into targets_gift values (66, 40);
insert into targets_gift values (69, 40);
insert into targets_gift values (73, 40);
insert into targets_gift values (75, 40);
insert into targets_gift values (76, 40);
insert into targets_gift values (79, 40);
insert into targets_gift values (80, 40);
insert into targets_gift values (81, 40);
insert into targets_gift values (82, 40);
insert into targets_gift values (84, 40);
insert into targets_gift values (90, 40);
insert into targets_gift values (92, 40);
insert into targets_gift values (93, 40);
insert into targets_gift values (94, 40);
insert into targets_gift values (95, 40);
insert into targets_gift values (97, 40);
insert into targets_gift values (98, 40);
insert into targets_gift values (101, 40);
insert into targets_gift values (103, 40);
insert into gift_targets values ('41', 'target_pal', 'pal', '3');
insert into targets_gift values (0, 41);
insert into targets_gift values (3, 41);
insert into targets_gift values (1, 41);
insert into targets_gift values (4, 41);
insert into targets_gift values (5, 41);
insert into targets_gift values (6, 41);
insert into targets_gift values (8, 41);
insert into targets_gift values (9, 41);
insert into targets_gift values (10, 41);
insert into targets_gift values (11, 41);
insert into targets_gift values (12, 41);
insert into targets_gift values (13, 41);
insert into targets_gift values (14, 41);
insert into targets_gift values (16, 41);
insert into targets_gift values (17, 41);
insert into targets_gift values (18, 41);
insert into targets_gift values (20, 41);
insert into targets_gift values (21, 41);
insert into targets_gift values (25, 41);
insert into targets_gift values (26, 41);
insert into targets_gift values (27, 41);
insert into targets_gift values (28, 41);
insert into targets_gift values (29, 41);
insert into targets_gift values (30, 41);
insert into targets_gift values (31, 41);
insert into targets_gift values (32, 41);
insert into targets_gift values (33, 41);
insert into targets_gift values (37, 41);
insert into targets_gift values (38, 41);
insert into targets_gift values (39, 41);
insert into targets_gift values (41, 41);
insert into targets_gift values (43, 41);
insert into targets_gift values (49, 41);
insert into targets_gift values (50, 41);
insert into targets_gift values (51, 41);
insert into targets_gift values (52, 41);
insert into targets_gift values (56, 41);
insert into targets_gift values (59, 41);
insert into targets_gift values (60, 41);
insert into targets_gift values (62, 41);
insert into targets_gift values (66, 41);
insert into targets_gift values (67, 41);
insert into targets_gift values (69, 41);
insert into targets_gift values (75, 41);
insert into targets_gift values (76, 41);
insert into targets_gift values (78, 41);
insert into targets_gift values (79, 41);
insert into targets_gift values (81, 41);
insert into targets_gift values (82, 41);
insert into targets_gift values (83, 41);
insert into targets_gift values (84, 41);
insert into targets_gift values (87, 41);
insert into targets_gift values (90, 41);
insert into targets_gift values (92, 41);
insert into targets_gift values (94, 41);
insert into targets_gift values (95, 41);
insert into targets_gift values (97, 41);
insert into targets_gift values (98, 41);
insert into targets_gift values (101, 41);
insert into targets_gift values (103, 41);
insert into targets_gift values (104, 41);


